### PR TITLE
Separated Basic, Extendable, and Custom servers

### PR DESCRIPTION
**Pull request by dleangen**
What was just "james-server" is now "james-custom-server" to avoid confusion.

I will mostly be working on "james-basic-server" for now, then eventually "james-extendable-server".

### CODE REVIEW

**Comment by ieugen** [comment]
Ok. If it makes sense, we can have configurations for each, in the respective directories + copy them duing docker image build. 

And .. you have a conflict in this PR.

**Comment by dleangen** [comment]
> Ok. If it makes sense, we can have configurations for each, in the respective directories + copy them duing docker image build.

Yes, that is exactly the idea. I was thinking that the conf dir would have all the files as a template. The templates can then be copied as needed, and the actual configs get included in the distro.

> And .. you have a conflict in this PR.

Ok, I'll look into it.

**Comment by dleangen** [comment]
There are currently no conflicts.

**Comment by dleangen** [comment]
Hold up. I am fixing an issue with the Docker image.

**Comment by dleangen** [comment]
Do you know what this is?

```
Exception in thread "main" org.apache.james.server.core.MissingArgumentException: Server needs a working.directory env entry
	at org.apache.james.server.core.configuration.Configuration$Basic$Builder.useWorkingDirectoryEnvProperty(Configuration.java:94)
	at ro.ieugen.sample.guice.MyCustomServerMain.main(MyCustomServerMain.java:85)
```

**Comment by dleangen** [comment]
Ok, it's working now. Sorry for the noise. There were a few little things that I did not immediately notice.

I will just continue working on this branch until this PR has been merged.

**Comment by ieugen** [comment]
Seems ok, thanks.

**Comment by dleangen** [comment]
Cool, thanks!

**Pull request merged**
