### PR TITLE
CLI is almost working

### PR DESCRIPTION
**Pull request by dleangen**
The CLI is almost working, but I am one step away.

When I execute it I get this:

```
$ docker run james-cli -h localhost -p 9999 listDomains
Error connecting to remote JMX agent : Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)]
```

I will continue tomorrow. If you have any comments please let me know.

### CODE REVIEW

**Comment by ieugen** [comment]
I think you're doing it wrong. 
The cli needs access to the ports of the server and by using docker run you effectively isolate it (that is the purpose of Docker). 

Package the cli in the same docker image as the server, or use it locally. 
If you package it in the same docker image as server you `docker exec` inside the james server and run in from there. 
You either docker exec a `bash` or directly the cli . 
https://docs.docker.com/engine/reference/commandline/exec/ 

docker run is for something else and IMO, it's not very useful in this scenario .

**Comment by dleangen** [comment]
My intent is to package up the CLI once, and to use it in docker-compose so that it is in the same docker network as the server.

**Comment by ieugen** [comment]
You package it once in the tar.gz.
You can package it also in the docker and publish it as a versioned image.
You can copy it to the docker server image FROM the docker cli image you built. 
Either way works, just keep in mind how they interact (http and/or jmx ) .
And make it easy on yourself :).

**Comment by dleangen** [comment]
Although I don't like it because I don't think it's the "right" way, I agree that it sure avoids a lot of trouble with Docker networking. For some reason I am still having a lot of trouble with it, so best to just avoid it.

I don't think this would be the right way to go in Kubernetes, though, but I'll push that off until later.

If you are ok with these changes, please merge. I will continue to push forward with the Basic Server and start looking into the Extendable Server.

**Comment by ieugen** [comment]
I think trying to build multiple variants here is a quite a lot of work and creates distractions.
I will indulge you.

**Comment by dleangen** [comment]
I agree. The only reason I am doing it this way is to not interfere with what you are trying to do. In the end, they should all be removed.

**Comment by ieugen** [comment]
Thanks.
I think we have enough of overlap that we can work on the same thing for more time.
Even if we have different implementations, they could share the same source.
We will start to diverge probably when it's closer to ready. 
This does not mean we need to change anything in the repo now, just to have in mind.

**Pull request merged**
